# frozen_string_literal: true

module Commiti
  class ConfigError < StandardError; end
end

require_relative 'services/clients/base_client'
require_relative 'services/git/git_reader'
require_relative 'services/git/git_writer'
require_relative 'services/style_analyzer'
require_relative 'services/text_generation_style'
require_relative 'services/clients/google_client'
require_relative 'services/clients/openai_client'
require_relative 'services/clients/anthropic_client'
require_relative 'services/clients/ollama_client'
require_relative 'services/client_factory'
require_relative 'services/helpers/config_loader'
require_relative 'services/git/diff_parser'
require_relative 'services/diff_summarization/diff_summarizer'
require_relative 'services/helpers/prompt_builder'
require_relative 'services/helpers/interactive_prompt'
require_relative 'services/git/pr/pr_opener'
require_relative 'services/git/pr/pr_creator'
require_relative 'services/helpers/clipboard'
require_relative 'services/helpers/terminal_ui'
require_relative 'services/helpers/spinner'
require_relative 'services/flow_context_builder'
require_relative 'services/message_generator'
require_relative 'services/message_presenter'
require_relative 'services/git/commit/commit_staging'
require_relative 'services/git/commit/commit_execution'
require_relative 'services/git/commit/change_grouping'
require_relative 'services/git/commit/group_editor'
require_relative 'flows/base_flow'
require_relative 'flows/commit_flow'
require_relative 'flows/changelog_flow'
require_relative 'flows/pr_flow'
require_relative 'flows/init_flow'
require_relative 'flows/doctor_flow'
